repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        name: Check YAML
        description: Check YAML files for parseable syntax
      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensure that a file is either empty or ends with one newline
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: Remove trailing whitespace
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings
      - id: check-case-conflict
        name: Check for case conflicts
        description: Check for files that would conflict in case-insensitive filesystems
      - id: check-toml
        name: Check TOML
        description: Check TOML files for parseable syntax
      - id: check-json
        name: Check JSON
        description: Check JSON files for parseable syntax
      - id: check-added-large-files
        name: Check for added large files
        description: Prevent giant files from being committed

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Black
        description: The uncompromising Python code formatter
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        name: Ruff
        description: An extremely fast Python linter
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: Ruff Formatter
        description: An extremely fast Python formatter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: MyPy
        description: Static type checker for Python
        additional_dependencies: [types-all]
        args: [--strict, --ignore-missing-imports]
